### ISSUE TITLE
UI issue - create your school page

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#10]
possibly <b>Not</b> a customer facing page -> the create a school page does not have "Go Back" btn option.

**Comment by sakihayashi** [comment]
this was intentional. I fixed it anyway. I will check when it's re-deployed.

**Comment by elicaballero** [comment]
Verified the fix, looks good and working as expected

**Comment by sakihayashi** [comment]
Sounds great. I will close this issue.
