### ISSUE TITLE
Admin log in concern 

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#11]
The admin login page is asking for the Key (ie: NewSchool#) should this say "School Password" ? 

<img width="689" alt="Screen Shot 2020-04-21 at 9 46 25 AM" src="https://user-images.githubusercontent.com/60198845/79873485-2ae21400-83b5-11ea-814e-5ccfc78d0980.png">

**Comment by sakihayashi** [comment]
That is my bad. I should be PW. I fixed it.

**Comment by elicaballero** [comment]
Verified the update, looks good

**Comment by sakihayashi** [comment]
Sounds great. I will close this issue.
