### ISSUE TITLE
Claim account page UI issue 

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#12]
Confirm password field is broken 

<img width="583" alt="Screen Shot 2020-04-21 at 12 40 20 PM" src="https://user-images.githubusercontent.com/60198845/79890287-46591900-83cd-11ea-88cf-6fe139b13797.png">

**Comment by sakihayashi** [comment]
Fixed it.

**Comment by elicaballero** [comment]
Verified the fix, looks good!

**Comment by sakihayashi** [comment]
Sounds great, I will close this issue.
