### ISSUE TITLE
UI concern on admin page

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#13]
Should the "Gear" icon be in the right top corner of the admin page to edit school info? I am also noticing there is no logout/back button once the school setup is successful.

<img width="677" alt="Screen Shot 2020-04-27 at 11 18 18 AM" src="https://user-images.githubusercontent.com/60198845/80389263-de954900-8878-11ea-87a8-f4396f7b1fda.png">

**Comment by sakihayashi** [comment]
@elicaballero it does not happen when I checked it with Chrome and Firefox. If you give me more details via slack, it'd be great. I sent a message via slack about it.

**Comment by sakihayashi** [comment]
it's verified. I will close this.
