### ISSUE TITLE
Longer course names are causing text to save behind attendance button

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#14]
If a professor saves a course name that is longer than usual or with special characters, this is causing the text to extend out behind the Attendance button. Any concern here? Not sure what the likelihood of longer course names will be.

<img width="657" alt="Screen Shot 2020-04-27 at 11 33 05 AM" src="https://user-images.githubusercontent.com/60198845/80391186-6714e900-887b-11ea-8c49-cdd15465a672.png">

**Comment by sakihayashi** [comment]
@elicaballero it does not happen on my side with Chrome and Firefox. If you give me more details, it'd be great like the browser and version info. 

<img width="776" alt="Screen Shot 2020-04-27 at 7 54 53 PM" src="https://user-images.githubusercontent.com/5385193/80432015-04ded700-88c1-11ea-8c4e-2f7eaa69540a.png">

**Comment by sakihayashi** [comment]
It's verified. I close this issue.
