### ISSUE TITLE
Case sensitive student id for log in 

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#15]
When a student user tries to log in, if the student id was capitalized when the CSV was saved, the user will need to enter the student id in the same format. 

<img width="661" alt="Screen Shot 2020-04-27 at 11 47 29 AM" src="https://user-images.githubusercontent.com/60198845/80392255-e6ef8300-887c-11ea-9136-f569336cf37b.png">

**Comment by sakihayashi** [comment]
The student ID works like a PW here. It is intentionally case sensitive. I close this.
