### ISSUE TITLE
Mark your attendance error message issue  

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#16]
When a student enters invalid class id / attendance code the error message is stating invalid "Test Key" - Should this state "Attendance code / ID " 

<img width="643" alt="Screen Shot 2020-04-27 at 11 51 21 AM" src="https://user-images.githubusercontent.com/60198845/80393361-629dff80-887e-11ea-9360-b6380efb1379.png">

**Comment by sakihayashi** [comment]
I fixed it.

**Comment by elicaballero** [comment]
On the current demo site build, this error message is showing as:  Invalid Class ID or Test Key. Please try again. Not sure if your changes were deployed

**Comment by sakihayashi** [comment]
The fix is verified so I will close this.
