### ISSUE TITLE
Accessibility Testing

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#18]
> this ticket will be used to measure accessibility issues/concerns

**Comment by elicaballero** [comment]
**Issue #1** - Adequate contrast is necessary for all users, especially users with low vision.
<img width="687" alt="Screen Shot 2020-04-27 at 12 33 19 PM" src="https://user-images.githubusercontent.com/60198845/80396860-4e103600-8883-11ea-9945-5854dfb75edc.png">

**Comment by elicaballero** [comment]
**Issue #2** - Broken ARIA reference - The target for the reference does not exist within all the user email fields.

**Comment by elicaballero** [comment]
**Issue #3** - Missing form label within all text fields. Form control does not have a corresponding label.

**Comment by sakihayashi** [comment]
> **Issue #2** - Broken ARIA reference - The target for the reference does not exist within all the user email fields.

Could you clarify it, please? I don't understand it.

**Comment by sakihayashi** [comment]
> **Issue #3** - Missing form label within all text fields. Form control does not have a corresponding label.

Could you clarify this, please? I don't have any form on this page so I don't understand what you pointed out.

**Comment by elicaballero** [comment]
Im thinking this may be a bootstrap issue, if bootstrap was used for these fields. Don't think these are big accessibility stoppers. But these errors are coming through on wave accessibility testing.
<img width="593" alt="Screen Shot 2020-04-28 at 11 48 18 AM" src="https://user-images.githubusercontent.com/60198845/80509128-f3401280-8946-11ea-9c55-11aa84d831d7.png">

**Comment by sakihayashi** [comment]
I see. I will look into it.

**Comment by sakihayashi** [comment]
I fixed it. Please check when we have next re-deploy.

**Comment by elicaballero** [comment]
As of the recent deploy on the demo site, i am not seeing any changes made.

**Comment by sakihayashi** [comment]
@elicaballero I think the portion is the latest change that has pending changes so it's not deployed yet I think. If you can check other issues first, it'd be great like issues #2, #3...so that I can make sure how many issues I need to work on.

**Comment by elicaballero** [comment]
@sakihayashi issues 2 & 3 are not showing as fixed on my end

**Comment by sakihayashi** [comment]
How about the others?

**Comment by sakihayashi** [comment]
It's verified so I will close this.
