### ISSUE TITLE
Accepting terms of use concern

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#19]
Clicking "Submit" before entering required information shows an error message to accept terms and conditions. After checking the terms of use, an error shows "Claim professor account failed."

Should there be error validations within the form when trying to move forward. Also, I am not seeing an option to view terms. 

<img width="718" alt="Screen Shot 2020-05-11 at 2 51 49 PM" src="https://user-images.githubusercontent.com/60198845/81600420-8e99a480-9397-11ea-93c4-064df17c2d98.png">

<img width="712" alt="Screen Shot 2020-05-11 at 2 57 34 PM" src="https://user-images.githubusercontent.com/60198845/81600531-c4d72400-9397-11ea-9c38-cba78d68da2c.png">

**Comment by sakihayashi** [comment]
Good find! I fixed all the required input now. Please verify when it's re-deployed.

**Comment by elicaballero** [comment]
Confirmed the updated error validations, looks good.

**Comment by sakihayashi** [comment]
Sounds great. I will close this issue.
