### ISSUE TITLE
Link issue "What’s my student ID?" 

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#2]
What’s my student ID? This link doesn't seem to have any function, should this open a modal for the user to retrieve the student id or explain what the user should enter into the field. Issue #1 in the google doc provided. 

https://docs.google.com/document/d/136_7Lo7z-ra40YhrlzKfPbWTsZU2AsuHqTrZgOeytKY/edit?usp=sharing

**Comment by sakihayashi** [comment]
I added tooltips for this.

**Comment by elicaballero** [comment]
@sakihayashi Im noticing when the cursor is placed over the text and outside of the text the tooltip is appearing without clicking  the actual link. 

<img width="746" alt="Screen Shot 2020-04-20 at 12 57 35 PM" src="https://user-images.githubusercontent.com/60198845/79778514-d41e0100-8306-11ea-8758-57df9273bf59.png">

**Comment by sakihayashi** [comment]
@elicaballero I fixed it. Let's check at the next deployment.

**Comment by sakihayashi** [comment]
I close this as I've got verification from Eli.

**Comment by sakihayashi** [comment]
I close this
