### ISSUE TITLE
Validation error is incorrect 

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#20]
**Confirm email** is not an option. This error message is showing when the confirm password does not match

<img width="685" alt="Screen Shot 2020-05-11 at 3 06 59 PM" src="https://user-images.githubusercontent.com/60198845/81601593-1b912d80-9399-11ea-91e9-ebd74b982ea9.png">

**Comment by sakihayashi** [comment]
Thanks, @elicaballero ! I fixed it. Please, verify when it's re-deployed.

**Comment by elicaballero** [comment]
Verified the fixes, looks good.

**Comment by sakihayashi** [comment]
Sounds great. I will close this.
