### ISSUE TITLE
Link issue "What is my class id?"

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#3]
Link is not responsive when clicks on the link. Issue # 2 in the provided google doc. 

https://docs.google.com/document/d/136_7Lo7z-ra40YhrlzKfPbWTsZU2AsuHqTrZgOeytKY/edit?usp=sharing

**Comment by sakihayashi** [comment]
I added a tooltip for this. -will make sure on deployment as well.

**Comment by elicaballero** [comment]
Tooltip shows when user hovers over link. Seems to be working as expected

**Comment by sakihayashi** [comment]
It's verified so I will close this.
