### ISSUE TITLE
UI concern on the instructions page 

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#4]
Student test instructions, starts with 0? Should this begin with “1” as the first step? Issue # 3 on the google doc. 

https://docs.google.com/document/d/136_7Lo7z-ra40YhrlzKfPbWTsZU2AsuHqTrZgOeytKY/edit?usp=sharing

**Comment by sakihayashi** [comment]
I fixed it. I will close this when I make sure on re-deployment.

**Comment by sakihayashi** [comment]
It's fixed. It starts at #1 now. I will close it.
