### ISSUE TITLE
Refreshing page is causing user to be logged out 

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#5]
After a student successfully logs into an account, if the page is refreshed at any point before entering details for attendance or test. The account is logged out and sent back to the sign in page. (The probability of a student refreshing the page is slim)

In addition to this issue. When the page refreshes and the user is asked to log in again, the “Go back” button in the top left does not always work. 

https://docs.google.com/document/d/136_7Lo7z-ra40YhrlzKfPbWTsZU2AsuHqTrZgOeytKY/edit?usp=sharing

**Comment by sakihayashi** [comment]
I fixed it by using session storage. It should work fine when it's redeployed.

**Comment by elicaballero** [comment]
Verified the update, after refreshing page the user is not automatically logged out

**Comment by sakihayashi** [comment]
Sounds great. I will close this issue.
