### ISSUE TITLE
Link issue "Forgot password" 

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#6]
When a user clicks the link “Forgot password” This link is rendering a blank page.

**Comment by sakihayashi** [comment]
I added the flow and frontend. I still need to connect with the backend.

**Comment by sakihayashi** [comment]
It's completed so it's ready to be reviewed.

**Comment by elicaballero** [comment]
Looks good

**Comment by sakihayashi** [comment]
Sounds great. I will close this issue.
