### ISSUE TITLE
UI issue with "Create Course" link 

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#7]
When creating a course, the “Create Course” does not signify its a clickable link when hovered over, also once the create course link has been clicked, there is no way to cancel the creation of course.

**Comment by sakihayashi** [comment]
I made it reversing the background and text color on hover. you can check it on when it's re-deployed.

**Comment by sakihayashi** [comment]
@elicaballero Can I close this?

**Comment by sakihayashi** [comment]
It's verified so I close this.
