### ISSUE TITLE
Case sensitive class id

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#8]
I noticed when entering the entering class id, this was case sensitive  based on how the professor has the course id written. Any concern with this? 

<img width="758" alt="Screen Shot 2020-04-13 at 2 22 29 PM" src="https://user-images.githubusercontent.com/60198845/79150938-9ade1200-7d97-11ea-94e0-cbbb4d8b1e67.png">

**Comment by cucucachu** [comment]
This should be fixed by my latest back-end changes. Please retest, and also  test that as a professor, I cannot create two courses with the same classId, regardless of case.

**Comment by elicaballero** [comment]
Tested on 4/21/2020 1:54 

Verified the above concern - course with matching classid and course name as an existing course is not creating the second course. 

<img width="676" alt="Screen Shot 2020-04-21 at 1 54 04 PM" src="https://user-images.githubusercontent.com/60198845/79897370-a2289f80-83d7-11ea-97a9-df0b1b68c6fd.png">

**Comment by sakihayashi** [comment]
It's intentional. We can create two courses having the same name but not the ID. The professors have to have a unique ID to create a new course.
