### ISSUE TITLE
Browser issues - MacOS / Windows 

### ISSUE THREAD

**Issue by elicaballero** [sakihayashi/wise-online-frontend#9]
1. Verified on the latest Mac OS, Safari 13 is not rendering the courses page when logging in as a professor. 

2. Windows 10 OS, IE 11 does not show log in page for any user.  Also the main site's landing page (https://wiseattend.com/) has broken links throughout the page.

**Comment by sakihayashi** [comment]
@elicaballero 
we are checking the bugs. 
we do not touch this main landing page at all by the way->  https://wiseattend.com/

**Comment by sakihayashi** [comment]
I will close this as we have nothing to do.
